<?php
// database/seeders/pages/SectionConfigsTableSeeder.php

namespace Database\Seeders\pages;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SectionConfigsTableSeeder extends Seeder
{
  public function run(): void
  {
    $sectionConfigs = [
      [
        'id' => 1,
        'page_slug' => 'home',
        'section_key' => 'banner',
        'component' => 'HomeBanner',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"home-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 2,
        'page_slug' => 'home',
        'section_key' => 'about-us',
        'component' => 'AboutUsSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'aboutUsData',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => null,
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 3,
        'page_slug' => 'home',
        'section_key' => 'our-action',
        'component' => 'OurActionSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'ourActionData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => null,
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 4,
        'page_slug' => 'home',
        'section_key' => 'where-we-work',
        'component' => 'WhereWeWorkSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'whereWeWorkData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => null,
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 5,
        'page_slug' => 'home',
        'section_key' => 'our-programs',
        'component' => 'OurProgramsSection',
        'data_table' => 'programs',
        'data_key' => 'ourProgramsData',
        'prop_name' => 'data',
        'display_order' => 5,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"limit":3,"showFeatured":true}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 6,  // Reusing same ID
        'page_slug' => 'home',
        'section_key' => 'stories',
        'component' => 'StoriesSection',
        'data_table' => 'shared_data',
        'data_key' => 'storiesData',
        'prop_name' => 'data',
        'display_order' => 6,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 7,
        'page_slug' => 'home',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 7,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => null,
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 8,
        'page_slug' => 'home',
        'section_key' => 'jobs',
        'component' => 'JobsSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'jobsData',
        'prop_name' => 'data',
        'display_order' => 8,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => null,
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 9,
        'page_slug' => 'home',
        'section_key' => 'program-impact',
        'component' => 'ProgramImpactSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'programImpactData',
        'prop_name' => 'data',
        'display_order' => 9,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => null,
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 10,
        'page_slug' => 'about',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"about-us-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 11,
        'page_slug' => 'about',
        'section_key' => 'background',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'backgroundData',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-left","sectionId":"background"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 12,
        'page_slug' => 'about',
        'section_key' => 'vision-mission',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'visionMissionData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-right","sectionId":"vision-and-mission","bgColor":"bg-[#F5F5F5]"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 13,
        'page_slug' => 'about',
        'section_key' => 'interventional',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'interventionalData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-left","sectionId":"interventional-approaches"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 14,
        'page_slug' => 'about',
        'section_key' => 'legal',
        'component' => 'LegalSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'legalData',
        'prop_name' => 'data',
        'display_order' => 5,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 15,
        'page_slug' => 'about',
        'section_key' => 'evolutionary',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'evolutionaryData',
        'prop_name' => 'data',
        'display_order' => 6,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-left","sectionId":"evolutionary-changes"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 16,
        'page_slug' => 'about',
        'section_key' => 'governance',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'governanceData',
        'prop_name' => 'data',
        'display_order' => 7,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-right","sectionId":"governance","bgColor":"bg-[#F5F5F5]"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 17,
        'page_slug' => 'about',
        'section_key' => 'cards',
        'component' => 'CardsSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'cardsData',
        'prop_name' => 'data',
        'display_order' => 8,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 18,
        'page_slug' => 'about',
        'section_key' => 'programs-activities',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'programsActivitiesData',
        'prop_name' => 'data',
        'display_order' => 9,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-right","sectionId":"programs-activities","bgColor":"bg-[#F5F5F5]"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 19,
        'page_slug' => 'about',
        'section_key' => 'training',
        'component' => 'HeroFigureSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'trainingData',
        'prop_name' => 'data',
        'display_order' => 10,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"layout":"text-left","sectionId":"training"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 20,
        'page_slug' => 'about',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 11,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 21,
        'page_slug' => 'about-details',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"about-details-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 22,
        'page_slug' => 'about-details',
        'section_key' => 'content',
        'component' => 'ContentSection',
        'data_table' => 'about_content',
        'data_key' => 'contentSectionData',
        'prop_name' => 'subPageData',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 1,
        'custom_props' => '{"bgColor":"bg-white","paddingY":"py-37.5","paddingX":"px-100","sectionId":"main-content"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 23,
        'page_slug' => 'about-details',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 24,
        'page_slug' => 'about-details',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 25,
        'page_slug' => 'projects-programs',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"projects-programs-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 26,
        'page_slug' => 'projects-programs',
        'section_key' => 'our-programs',
        'component' => 'OurProgramsSection',
        'data_table' => 'programs',
        'data_key' => 'ourProgramsData',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"limit":null,"showFeatured":false,"showHeader":false}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 27,
        'page_slug' => 'projects-programs',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 28,
        'page_slug' => 'projects-programs-details',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 29,
        'page_slug' => 'projects-programs-details',
        'section_key' => 'content',
        'component' => 'ProgramContentSection',
        'data_table' => 'programs',
        'data_key' => 'programContentData',
        'prop_name' => 'programData',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 1,
        'custom_props' => '{"bgColor":"bg-white","paddingY":"py-37.5","paddingX":"px-100"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 30,
        'page_slug' => 'projects-programs-details',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 31,
        'page_slug' => 'projects-programs-details',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 32,
        'page_slug' => 'blog',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"blogs-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 33,
        'page_slug' => 'blog',
        'section_key' => 'blog-section',
        'component' => 'BlogSection',
        'data_table' => 'blogs',
        'data_key' => 'blogsData',
        'prop_name' => 'blogsData',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 34,
        'page_slug' => 'blog',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 35,
        'page_slug' => 'blog-details',
        'section_key' => 'banner',
        'component' => 'BannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'bannerData',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"blog-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 36,
        'page_slug' => 'blog-details',
        'section_key' => 'content',
        'component' => 'BlogContentSection',
        'data_table' => 'blogs',
        'data_key' => 'blogData',
        'prop_name' => 'blogData',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 0,
        'custom_props' => '{"bgColor":"bg-white","paddingY":"py-12 lg:py-16","paddingX":"px-4","sectionId":"blog-content"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 37,
        'page_slug' => 'blog-details',
        'section_key' => 'related-blogs',
        'component' => 'BlogSection',
        'data_table' => 'blogs',
        'data_key' => 'relatedBlogsData',
        'prop_name' => 'blogsData',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"bgColor":"bg-[#F5F5F5]","sectionTitle":"Related Blogs","isRelated":true}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 38,
        'page_slug' => 'blog-details',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 39,
        'page_slug' => 'contact',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"contact-us-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 40,
        'page_slug' => 'contact',
        'section_key' => 'contact-offices',
        'component' => 'ContactOfficeSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'offices',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 41,
        'page_slug' => 'contact',
        'section_key' => 'contact-reach',
        'component' => 'ContactReachSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'reachUsData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 42,
        'page_slug' => 'contact',
        'section_key' => 'follow-us',
        'component' => 'FollowUSSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'socialItems',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 43,
        'page_slug' => 'contact',
        'section_key' => 'address',
        'component' => 'AddressSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'officesLocation',
        'prop_name' => 'data',
        'display_order' => 5,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 44,
        'page_slug' => 'contact',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 6,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"bgColor":"bg-white"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 45,  // Reusing same ID
        'page_slug' => 'contact',
        'section_key' => 'stories',
        'component' => 'StoriesSection',
        'data_table' => 'shared_data',  // CHANGED from custom_section_data to shared_data
        'data_key' => 'storiesData',
        'prop_name' => 'data',
        'display_order' => 7,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 46,
        'page_slug' => 'contact',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 8,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],

      // ============================================
      // PUBLICATIONS PAGE (formerly Media)
      // ============================================
      [
        'id' => 47,
        'page_slug' => 'publications',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"publications-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 48,
        'page_slug' => 'publications',
        'section_key' => 'publications-section',
        'component' => 'PublicationsSection',
        'data_table' => 'publications',
        'data_key' => 'publicationsData',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 1,
        'custom_props' => '{"sectionTitle":"Our Publications","bgColor":"bg-white"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 49,
        'page_slug' => 'publications',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 50,  // Reusing same ID
        'page_slug' => 'publications',
        'section_key' => 'stories',
        'component' => 'StoriesSection',
        'data_table' => 'shared_data',
        'data_key' => 'storiesData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 51,
        'page_slug' => 'publications',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 5,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],

      // ============================================
      // PUBLICATIONS DETAILS PAGE (formerly Media Details)
      // ============================================
      [
        'id' => 52,
        'page_slug' => 'publications-details',
        'section_key' => 'banner',
        'component' => 'BannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'bannerData',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"publications-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 53,
        'page_slug' => 'publications-details',
        'section_key' => 'content',
        'component' => 'PublicationContentSection',
        'data_table' => 'publications',
        'data_key' => 'publicationData',
        'prop_name' => 'publicationData',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 1,
        'custom_props' => '{"bgColor":"bg-white","paddingY":"py-12 lg:py-16","paddingX":"px-4","sectionId":"publication-content"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 54,
        'page_slug' => 'publications-details',
        'section_key' => 'related-publications',
        'component' => 'RelatedPublicationsSection',
        'data_table' => 'publications',
        'data_key' => 'relatedPublicationsData',
        'prop_name' => 'publicationsData',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 1,
        'custom_props' => '{"bgColor":"bg-[#F5F5F5]","title":"Related Publications","isRelated":true}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 55,
        'page_slug' => 'publications-details',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],

      // ============================================
      // GALLERY PAGE
      // ============================================
      [
        'id' => 56,
        'page_slug' => 'gallery',
        'section_key' => 'banner',
        'component' => 'PageTagBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"gallery-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 57,
        'page_slug' => 'gallery',
        'section_key' => 'image-gallery',
        'component' => 'ImageGallerySection',
        'data_table' => 'custom_section_data',
        'data_key' => 'imageGalleryData',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 58,
        'page_slug' => 'gallery',
        'section_key' => 'video-gallery',
        'component' => 'VideoGallerySection',
        'data_table' => 'custom_section_data',
        'data_key' => 'videoGalleryData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 59,
        'page_slug' => 'gallery',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 60,
        'page_slug' => 'gallery',
        'section_key' => 'stories',
        'component' => 'StoriesSection',
        'data_table' => 'shared_data',
        'data_key' => 'storiesData',
        'prop_name' => 'data',
        'display_order' => 5,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 61,
        'page_slug' => 'gallery',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 6,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],

      // ============================================
      // JOBS PAGE CONFIGURATIONS
      // ============================================
      [
        'id' => 62,
        'page_slug' => 'jobs',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"jobs-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 63,
        'page_slug' => 'jobs',
        'section_key' => 'jobs',
        'component' => 'JobsSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'jobsData',
        'prop_name' => 'jobsData',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 1,
        'custom_props' => '{"bgColor":"bg-white","paddingY":"py-12 lg:py-16"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 64,
        'page_slug' => 'jobs',
        'section_key' => 'faq',
        'component' => 'FAQSection',
        'data_table' => 'shared_data',
        'data_key' => 'faqData',
        'prop_name' => 'data',
        'display_order' => 3,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 65,
        'page_slug' => 'jobs',
        'section_key' => 'stories',
        'component' => 'StoriesSection',
        'data_table' => 'shared_data',
        'data_key' => 'storiesData',
        'prop_name' => 'data',
        'display_order' => 4,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 66,
        'page_slug' => 'jobs',
        'section_key' => 'upcoming-events',
        'component' => 'UpcomingEventsSection',
        'data_table' => 'shared_data',
        'data_key' => 'upcomingEventsData',
        'prop_name' => 'data',
        'display_order' => 5,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '[]',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],

      // ============================================
      // JOBS DETAILS PAGE CONFIGURATIONS
      // ============================================
      [
        'id' => 67,
        'page_slug' => 'jobs-details',
        'section_key' => 'banner',
        'component' => 'PageBannerSection',
        'data_table' => 'custom_section_data',
        'data_key' => 'bannerData',
        'prop_name' => 'data',
        'display_order' => 1,
        'is_enabled' => 1,
        'is_fixed_section' => 0,
        'is_special_component' => 0,
        'custom_props' => '{"sectionId":"jobs-details-banner"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],
      [
        'id' => 68,
        'page_slug' => 'jobs-details',
        'section_key' => 'content',
        'component' => 'JobDetailsContentSection', 
        'data_table' => 'job_details', 
        'data_key' => 'jobDetailsData',
        'prop_name' => 'data',
        'display_order' => 2,
        'is_enabled' => 1,
        'is_fixed_section' => 1,
        'is_special_component' => 1,
        'custom_props' => '{"bgColor":"bg-white","paddingY":"py-12 lg:py-16","paddingX":"px-4"}',
        'created_at' => '2024-01-01 00:00:00',
        'updated_at' => '2024-01-01 00:00:00',
      ],


    ];

    DB::table('section_configs')->insert($sectionConfigs);
  }
}
