// resources/js/pages/Backend/CMS/Pages/Index.jsx

// React
import React, { useState, useMemo, useEffect } from 'react';
import { Head, Link, router } from '@inertiajs/react';

// Layout
import AuthenticatedLayout from '../../../../layouts/AuthenticatedLayout';

// Auth
import { useAuth } from '../../../../hooks/useAuth';

// SweetAlert
import Swal from 'sweetalert2';

// Icons
import {
  FaPlus,
  FaEdit,
  FaTrash,
  FaEye,
  FaSpinner,
  FaFileAlt,
  FaCheckCircle,
  FaBan,
  FaToggleOn,
  FaToggleOff,
  FaChevronLeft,
  FaChevronRight,
  FaShieldAlt,
  FaHome,
  FaInfoCircle,
  FaLink,
  FaTimes,
  FaSave,
  FaMagic,
  FaLayerGroup,  // ← NEW: Sections icon
} from 'react-icons/fa';

export default function PagesIndex({ pages }) {
  const { hasAnyPermission, hasRole } = useAuth();

  // Permission checks
  const canCreate = hasAnyPermission(['pages.create', 'pages.manage']);
  const canEdit = hasAnyPermission(['pages.update', 'pages.manage']);
  const canDelete = hasAnyPermission(['pages.destroy', 'pages.manage']);
  const canViewCMS = hasAnyPermission(['pages.view', 'pages.manage']);

  // States
  const [deletingId, setDeletingId] = useState(null);
  const [togglingId, setTogglingId] = useState(null);

  // Modal states
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingPage, setEditingPage] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formErrors, setFormErrors] = useState({});
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);

  // Form state
  const [formData, setFormData] = useState({
    slug: '',
    name: '',
    title: '',
    description: '',
    is_active: true,
  });

  // Protected pages that cannot be deleted
  const PROTECTED_SLUGS = ['home'];
  const PROTECTED_NAMES = ['Home'];

  // Check if a page is protected (only 'home' is protected now)
  const isProtectedPage = (page) => {
    return PROTECTED_SLUGS.includes(page.slug) || PROTECTED_NAMES.includes(page.name);
  };

  // Check if a page is a details/subpage (slug ends with '-details')
  const isDetailsPage = (page) => {
    return page.slug?.endsWith('-details') || false;
  };

  // Check if a page is the main details page (exact match 'details')
  const isMainDetailsPage = (page) => {
    return page.slug === 'details' || page.name === 'Details';
  };

  /**
   * Generate a slug from a string
   * Converts to lowercase, replaces spaces with hyphens, removes special chars
   */
  const generateSlug = (text) => {
    if (!text) return '';
    return text
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-'); // Replace multiple hyphens with single
  };

  /**
   * Check if slug already exists (excluding current page if editing)
   */
  const isSlugUnique = (slug, excludeId = null) => {
    return !pages.some(p =>
      p.slug === slug &&
      (excludeId === null || p.id !== excludeId)
    );
  };

  /**
   * Generate a unique slug by appending a number if needed
   */
  const generateUniqueSlug = (baseSlug, excludeId = null) => {
    let slug = baseSlug;
    let counter = 1;

    while (!isSlugUnique(slug, excludeId)) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }

    return slug;
  };

  // Auto-generate slug when name changes (only for new pages)
  useEffect(() => {
    if (!editingPage && isSlugAutoGenerated && formData.name) {
      const baseSlug = generateSlug(formData.name);
      const uniqueSlug = generateUniqueSlug(baseSlug);
      setFormData(prev => ({ ...prev, slug: uniqueSlug }));
    }
  }, [formData.name, editingPage, isSlugAutoGenerated]);

  // Auto-generate slug when editing and name changes (if slug was auto-generated)
  useEffect(() => {
    if (editingPage && isSlugAutoGenerated && formData.name) {
      // Only auto-update slug if it was originally auto-generated or matches the old name
      const oldSlug = editingPage.slug;
      const nameSlug = generateSlug(formData.name);

      // If the current slug matches the old slug or was auto-generated from name
      if (oldSlug === generateSlug(editingPage.name) || oldSlug === formData.slug) {
        const baseSlug = generateSlug(formData.name);
        const uniqueSlug = generateUniqueSlug(baseSlug, editingPage.id);
        setFormData(prev => ({ ...prev, slug: uniqueSlug }));
      }
    }
  }, [formData.name, editingPage, isSlugAutoGenerated]);

  // Get parent slug from details page
  const getParentCandidates = (slug) => {
    if (!slug || !slug.endsWith('-details')) return [];

    const base = slug.replace('-details', '');
    const candidates = [base];

    if (base.endsWith('s') && base.length > 1) {
      candidates.push(base.slice(0, -1));
    } else if (!base.endsWith('s')) {
      candidates.push(base + 's');
    }

    return candidates;
  };

  /**
   * Find the actual parent page for a details page
   * Checks all candidate variations
   */
  const findParentPage = (detailsPage, allPages) => {
    const candidates = getParentCandidates(detailsPage.slug);

    for (const candidate of candidates) {
      const parent = allPages.find(p =>
        p.slug === candidate &&
        !isDetailsPage(p) &&
        !isMainDetailsPage(p)
      );
      if (parent) return parent;
    }

    return null;
  };

  // Check if a page has details subpage
  const hasDetailsSubpage = (page, allPages) => {
    // Check exact match
    if (allPages.some(p => p.slug === `${page.slug}-details` && !isMainDetailsPage(p))) {
      return true;
    }
    // Check plural/singular variations
    if (page.slug.endsWith('s') && page.slug.length > 1) {
      const singular = page.slug.slice(0, -1);
      if (allPages.some(p => p.slug === `${singular}-details` && !isMainDetailsPage(p))) {
        return true;
      }
    } else if (!page.slug.endsWith('s')) {
      const plural = page.slug + 's';
      if (allPages.some(p => p.slug === `${plural}-details` && !isMainDetailsPage(p))) {
        return true;
      }
    }
    return false;
  };

  // Sort pages: Home first, then main pages, then details pages at the end
  const sortedPages = useMemo(() => {
    if (!pages || pages.length === 0) return [];

    const homePage = pages.find(p => p.slug === 'home' || p.name === 'Home');
    const mainDetailsPage = pages.find(p => isMainDetailsPage(p));
    const detailsPages = pages.filter(p => isDetailsPage(p) && !isMainDetailsPage(p));
    const mainPages = pages.filter(p =>
      p.slug !== 'home' && p.name !== 'Home' &&
      !isMainDetailsPage(p) &&
      !isDetailsPage(p)
    );

    const sortedMain = [...mainPages].sort((a, b) => a.name.localeCompare(b.name));
    const sortedDetails = [...detailsPages].sort((a, b) => {
      const parentA = findParentPage(a, pages);
      const parentB = findParentPage(b, pages);

      if (parentA && parentB) {
        return parentA.name.localeCompare(parentB.name);
      }
      if (parentA) return -1;
      if (parentB) return 1;
      return a.name.localeCompare(b.name);
    });

    const result = [];
    if (homePage) result.push(homePage);
    result.push(...sortedMain);
    if (mainDetailsPage) result.push(mainDetailsPage);
    result.push(...sortedDetails);

    return result;
  }, [pages]);

  // If user doesn't have permission, show access denied
  if (!canViewCMS) {
    return (
      <AuthenticatedLayout>
        <Head title="Access Denied" />
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
          <div className="text-center">
            <div className="w-20 h-20 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <FaShieldAlt className="w-10 h-10 text-red-500" />
            </div>
            <h2 className="text-xl font-semibold text-gray-900">Access Denied</h2>
            <p className="text-gray-500 mt-2">You don't have permission to view pages.</p>
          </div>
        </div>
      </AuthenticatedLayout>
    );
  }

  // ==========================================
  // MODAL HANDLERS
  // ==========================================

  // Open create modal
  const handleOpenCreate = () => {
    setEditingPage(null);
    setFormData({
      slug: '',
      name: '',
      title: '',
      description: '',
      is_active: true,
    });
    setIsSlugAutoGenerated(true);
    setFormErrors({});
    setIsModalOpen(true);
  };

  // Open edit modal
  const handleOpenEdit = (page) => {
    setEditingPage(page);
    setFormData({
      slug: page.slug || '',
      name: page.name || '',
      title: page.title || '',
      description: page.description || '',
      is_active: page.is_active ?? true,
    });
    // Check if slug was auto-generated (matches name slug)
    const nameSlug = generateSlug(page.name);
    setIsSlugAutoGenerated(page.slug === nameSlug || page.slug === generateUniqueSlug(nameSlug, page.id));
    setFormErrors({});
    setIsModalOpen(true);
  };

  // Close modal
  const handleCloseModal = () => {
    setIsModalOpen(false);
    setEditingPage(null);
    setFormErrors({});
    setIsSlugAutoGenerated(true);
  };

  // Handle form input change
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    // If name changes and slug is auto-generated, update slug
    if (name === 'name' && isSlugAutoGenerated) {
      const baseSlug = generateSlug(value);
      const excludeId = editingPage?.id || null;
      const uniqueSlug = generateUniqueSlug(baseSlug, excludeId);
      setFormData(prev => ({
        ...prev,
        name: value,
        slug: uniqueSlug,
      }));
    } else if (name === 'slug') {
      // User manually edited slug, disable auto-generation
      setIsSlugAutoGenerated(false);
      setFormData(prev => ({ ...prev, slug: value }));
    } else {
      setFormData(prev => ({
        ...prev,
        [name]: type === 'checkbox' ? checked : value,
      }));
    }

    // Clear error for this field
    if (formErrors[name]) {
      setFormErrors(prev => ({ ...prev, [name]: undefined }));
    }
  };

  // Handle manual slug generation button click
  const handleAutoGenerateSlug = () => {
    if (formData.name) {
      const baseSlug = generateSlug(formData.name);
      const excludeId = editingPage?.id || null;
      const uniqueSlug = generateUniqueSlug(baseSlug, excludeId);
      setFormData(prev => ({ ...prev, slug: uniqueSlug }));
      setIsSlugAutoGenerated(true);
    }
  };

  // Handle form submit
  const handleSubmit = (e) => {
    e.preventDefault();

    // Validate
    const newErrors = {};
    if (!formData.slug.trim()) newErrors.slug = 'Slug is required';
    if (!formData.name.trim()) newErrors.name = 'Name is required';
    if (!formData.title.trim()) newErrors.title = 'Title is required';

    // Check slug uniqueness
    if (formData.slug.trim() && !isSlugUnique(formData.slug, editingPage?.id)) {
      newErrors.slug = 'This slug is already taken. Please use a different one.';
    }

    if (Object.keys(newErrors).length > 0) {
      setFormErrors(newErrors);
      Swal.fire({
        icon: 'error',
        title: 'Validation Error',
        text: 'Please fix the errors before submitting.',
      });
      return;
    }

    setIsSubmitting(true);

    const isEdit = !!editingPage;
    const url = isEdit
      ? route('backend.cms.pages.update', editingPage.id)
      : route('backend.cms.pages.store');
    const method = isEdit ? 'put' : 'post';

    router[method](url, formData, {
      preserveScroll: true,
      onSuccess: () => {
        Swal.fire({
          icon: 'success',
          title: 'Success!',
          text: `Page ${isEdit ? 'updated' : 'created'} successfully.`,
          timer: 1500,
          showConfirmButton: false,
        });
        setIsModalOpen(false);
        router.reload();
      },
      onError: (error) => {
        if (error.response?.data?.errors) {
          setFormErrors(error.response.data.errors);
        }
        Swal.fire({
          icon: 'error',
          title: 'Failed',
          text: error?.message || `Failed to ${isEdit ? 'update' : 'create'} page.`,
        });
        setIsSubmitting(false);
      },
      onFinish: () => setIsSubmitting(false),
    });
  };

  // ==========================================
  // DELETE HANDLERS
  // ==========================================

  // Handle delete with protection check
  const handleDelete = (page) => {
    if (isProtectedPage(page)) {
      Swal.fire({
        icon: 'warning',
        title: 'Cannot Delete',
        text: `"${page.name}" is a protected system page and cannot be deleted.`,
        confirmButtonColor: '#3085d6',
        confirmButtonText: 'OK',
      });
      return;
    }

    if (isDetailsPage(page) || isMainDetailsPage(page)) {
      const parent = isDetailsPage(page) ? findParentPage(page, pages) : null;
      const parentName = parent ? parent.name : 'unknown';
      const warningMessage = parent
        ? `"${page.name}" is a details subpage for "${parentName}". Deleting it may affect the parent page's details section.`
        : `"${page.name}" is a details page. Deleting it may affect pages that reference it.`;

      Swal.fire({
        title: 'Delete Details Page?',
        text: warningMessage,
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        confirmButtonText: 'Yes, delete',
        cancelButtonText: 'Cancel',
      }).then((result) => {
        if (result.isConfirmed) {
          performDelete(page.id);
        }
      });
      return;
    }

    if (hasDetailsSubpage(page, pages)) {
      Swal.fire({
        title: 'Delete Page with Details?',
        text: `"${page.name}" has details subpages. Deleting this page will also affect its related details pages.`,
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        confirmButtonText: 'Yes, delete',
        cancelButtonText: 'Cancel',
      }).then((result) => {
        if (result.isConfirmed) {
          performDelete(page.id);
        }
      });
      return;
    }

    Swal.fire({
      title: 'Delete Page?',
      text: `Are you sure you want to delete "${page.name}"? This will move the page to trash. You can restore it later.`,
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#d33',
      cancelButtonColor: '#3085d6',
      confirmButtonText: 'Yes, delete',
      cancelButtonText: 'Cancel',
    }).then((result) => {
      if (result.isConfirmed) {
        performDelete(page.id);
      }
    });
  };

  // Perform the actual delete
  const performDelete = (id) => {
    setDeletingId(id);

    router.delete(route('backend.cms.pages.destroy', id), {
      preserveScroll: true,
      onSuccess: () => {
        Swal.fire({
          icon: 'success',
          title: 'Deleted!',
          text: 'Page moved to trash.',
          timer: 1500,
          showConfirmButton: false,
        });
        router.reload();
      },
      onError: (error) => {
        Swal.fire({
          icon: 'error',
          title: 'Delete Failed',
          text: error?.message || 'Failed to delete page.',
        });
      },
      onFinish: () => setDeletingId(null),
    });
  };

  // ==========================================
  // UI HELPERS
  // ==========================================

  // Get page icon based on slug
  const getPageIcon = (page) => {
    if (page.slug === 'home' || page.name === 'Home') {
      return FaHome;
    }
    if (isMainDetailsPage(page) || isDetailsPage(page)) {
      return FaInfoCircle;
    }
    return FaFileAlt;
  };

  // Get page type label
  const getPageTypeLabel = (page) => {
    if (page.slug === 'home' || page.name === 'Home') {
      return { label: 'Home', color: 'bg-green-100 text-green-800', icon: '🏠' };
    }
    if (isMainDetailsPage(page)) {
      return { label: 'Main Details', color: 'bg-purple-100 text-purple-800', icon: '📄' };
    }
    if (isDetailsPage(page)) {
      const parent = findParentPage(page, pages);
      const parentName = parent ? parent.name : getParentCandidates(page.slug)[0];
      return {
        label: `Subpage (${parentName})`,
        color: 'bg-indigo-100 text-indigo-800',
        icon: '📎',
        parent: parentName
      };
    }
    return { label: 'Standard', color: 'bg-gray-100 text-gray-600', icon: '📃' };
  };

  return (
    <AuthenticatedLayout>
      <Head title="Pages" />

      <div className="min-h-screen bg-linear-to-br from-gray-50 to-gray-100/50 p-6">
        <div className="mx-auto">
          {/* Header */}
          <div className="flex justify-between items-start mb-6">
            <div>
              <h1 className="text-3xl font-bold bg-linear-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
                Pages
              </h1>
              <p className="text-sm text-gray-500 mt-1">
                Manage your website pages
              </p>
              <div className="flex gap-3 mt-2 flex-wrap">
                <span className="inline-flex items-center gap-1 text-xs">
                  <span className="w-2 h-2 rounded-full bg-green-500"></span>
                  Active: {pages.filter(p => p.is_active).length}
                </span>
                <span className="inline-flex items-center gap-1 text-xs">
                  <span className="w-2 h-2 rounded-full bg-gray-400"></span>
                  Inactive: {pages.filter(p => !p.is_active).length}
                </span>
                <span className="inline-flex items-center gap-1 text-xs text-blue-600">
                  <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                  Total: {pages.length}
                </span>
                <span className="inline-flex items-center gap-1 text-xs text-purple-600">
                  <span className="w-2 h-2 rounded-full bg-purple-500"></span>
                  Details: {pages.filter(p => isDetailsPage(p) || isMainDetailsPage(p)).length}
                </span>
              </div>
            </div>
            {canCreate && (
              <button
                onClick={handleOpenCreate}
                className="bg-linear-to-r from-blue-600 to-blue-700 text-white px-5 py-2.5 rounded-lg flex items-center gap-2 hover:from-blue-700 hover:to-blue-800 transition-all duration-200 transform hover:scale-105 shadow-md hover:shadow-lg"
              >
                <FaPlus size={16} />
                Create Page
              </button>
            )}
          </div>

          {/* Table */}
          <div className="bg-white rounded-xl shadow-lg overflow-hidden">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                {/* Table Header */}
                <thead className="bg-linear-to-r from-gray-50 to-gray-100">
                  <tr>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Page
                    </th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Slug
                    </th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Type
                    </th>
                    <th className="px-6 py-4 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>

                {/* Table Body */}
                <tbody className="bg-white divide-y divide-gray-200">
                  {sortedPages.length === 0 && (
                    <tr>
                      <td colSpan="4" className="text-center py-16">
                        <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                          <FaFileAlt className="h-10 w-10 text-gray-400" />
                        </div>
                        <h3 className="text-lg font-medium text-gray-900">No pages found</h3>
                        <p className="mt-1 text-sm text-gray-500">Get started by creating your first page.</p>
                        {canCreate && (
                          <button
                            onClick={handleOpenCreate}
                            className="inline-flex items-center gap-2 mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
                          >
                            <FaPlus size={14} />
                            Create Page
                          </button>
                        )}
                      </td>
                    </tr>
                  )}

                  {sortedPages.map((page) => {
                    const isProtected = isProtectedPage(page);
                    const isDetails = isDetailsPage(page);
                    const isMainDetails = isMainDetailsPage(page);
                    const PageIcon = getPageIcon(page);
                    const typeInfo = getPageTypeLabel(page);
                    const isHome = page.slug === 'home' || page.name === 'Home';
                    const hasSubpage = hasDetailsSubpage(page, pages);

                    return (
                      <tr
                        key={page.id}
                        className={`hover:bg-gray-50 transition-all duration-200 ${isProtected ? 'bg-green-50/30' : ''
                          } ${isDetails || isMainDetails ? 'bg-purple-50/20' : ''
                          }`}
                      >
                        <td className="px-6 py-4">
                          <div className="flex items-center gap-3">
                            <div className={`w-10 h-10 rounded-lg flex items-center justify-center shrink-0 ${isProtected
                                ? 'bg-green-100'
                                : isDetails || isMainDetails
                                  ? 'bg-purple-100'
                                  : page.is_active ? 'bg-green-100' : 'bg-gray-100'
                              }`}>
                              <PageIcon className={
                                isProtected
                                  ? 'text-green-600'
                                  : isDetails || isMainDetails
                                    ? 'text-purple-600'
                                    : page.is_active ? 'text-green-600' : 'text-gray-400'
                              } size={18} />
                            </div>
                            <div>
                              <div className="font-semibold text-gray-900 flex items-center gap-2 flex-wrap">
                                {page.name}
                                {isProtected && (
                                  <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full">
                                    Protected
                                  </span>
                                )}
                                {isHome && (
                                  <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full">
                                    Home
                                  </span>
                                )}
                                {isMainDetails && (
                                  <span className="text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full">
                                    Main Details
                                  </span>
                                )}
                                {isDetails && !isMainDetails && (
                                  <span className="text-xs bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full">
                                    Subpage: {typeInfo.parent}
                                  </span>
                                )}
                                {hasSubpage && !isDetails && !isMainDetails && !isProtected && (
                                  <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full flex items-center gap-1">
                                    <FaLink size={10} />
                                    Has Sub Page
                                  </span>
                                )}
                              </div>
                              <div className="text-xs text-gray-500 mt-0.5">ID: #{page.id}</div>
                            </div>
                          </div>
                        </td>

                        <td className="px-6 py-4">
                          <code className="text-xs bg-gray-100 px-2 py-1 rounded text-gray-600">{page.slug}</code>
                        </td>

                        <td className="px-6 py-4">
                          <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-semibold ${typeInfo.color}`}>
                            <span>{typeInfo.icon}</span>
                            {typeInfo.label}
                          </span>
                        </td>

                        <td className="px-6 py-4 whitespace-nowrap text-right">
                          <div className="flex justify-end gap-2">
                            {/* Sections Button - NEW ICON */}
                            <Link
                              href={route('backend.cms.pages.sections', page.id)}
                              className="p-2 text-indigo-600 hover:text-indigo-900 hover:bg-indigo-50 rounded-lg transition-all duration-200 group"
                              title="Manage Sections"
                            >
                              <FaLayerGroup size={18} className="group-hover:scale-110 transition-transform duration-200" />
                            </Link>

                            {canEdit && (
                              <button
                                onClick={() => handleOpenEdit(page)}
                                className="p-2 text-blue-600 hover:text-blue-900 hover:bg-blue-50 rounded-lg transition-all duration-200"
                                title="Edit"
                              >
                                <FaEdit size={18} />
                              </button>
                            )}

                            {canDelete && (
                              <button
                                onClick={() => handleDelete(page)}
                                disabled={deletingId === page.id || isProtected}
                                className={`p-2 ${isProtected
                                    ? 'text-gray-400 cursor-not-allowed'
                                    : isDetails || isMainDetails
                                      ? 'text-orange-600 hover:text-orange-900 hover:bg-orange-50'
                                      : 'text-red-600 hover:text-red-900 hover:bg-red-50'
                                  } rounded-lg transition-all duration-200 ${deletingId === page.id ? 'opacity-50 cursor-not-allowed' : ''
                                  }`}
                                title={isProtected ? 'Protected pages cannot be deleted' : 'Delete'}
                              >
                                {deletingId === page.id ? (
                                  <FaSpinner className="animate-spin" size={18} />
                                ) : (
                                  <FaTrash size={18} />
                                )}
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      {/* ==========================================
          MODAL - Create/Edit Page
          ========================================== */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 animate-fade-in">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl mx-4 max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center p-6 border-b border-gray-200 sticky top-0 bg-white z-10 rounded-t-2xl">
              <div>
                <h2 className="text-xl font-semibold text-gray-900">
                  {editingPage ? 'Edit Page' : 'Create Page'}
                </h2>
                <p className="text-xs text-gray-500 mt-0.5">
                  {editingPage ? 'Update the page details' : 'Add a new page to your website'}
                </p>
              </div>
              <button
                onClick={handleCloseModal}
                className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors duration-200"
                disabled={isSubmitting}
              >
                <FaTimes size={20} />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="p-6 space-y-6">
              {/* Name */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Page Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  className={`w-full px-4 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 ${formErrors.name ? 'border-red-500' : 'border-gray-300'
                    }`}
                  placeholder="e.g., About Us, Contact, Services"
                  disabled={isSubmitting}
                />
                {formErrors.name && (
                  <p className="text-red-500 text-xs mt-1">{formErrors.name}</p>
                )}
                <p className="text-xs text-gray-400 mt-1">
                  The display name of the page. The slug will be auto-generated from this.
                </p>
              </div>

              {/* Slug with Auto-Generate */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Slug <span className="text-red-500">*</span>
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    name="slug"
                    value={formData.slug}
                    onChange={handleChange}
                    className={`flex-1 px-4 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 ${formErrors.slug ? 'border-red-500' : 'border-gray-300'
                      }`}
                    placeholder="e.g., about-us, contact, services"
                    disabled={isSubmitting}
                  />
                  <button
                    type="button"
                    onClick={handleAutoGenerateSlug}
                    disabled={!formData.name || isSubmitting}
                    className="px-4 py-2.5 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-all duration-200 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
                    title="Auto-generate slug from page name"
                  >
                    <FaMagic size={14} />
                    Generate
                  </button>
                </div>
                {formErrors.slug && (
                  <p className="text-red-500 text-xs mt-1">{formErrors.slug}</p>
                )}
                <div className="flex items-center gap-2 mt-1">
                  <input
                    type="checkbox"
                    checked={isSlugAutoGenerated}
                    onChange={(e) => setIsSlugAutoGenerated(e.target.checked)}
                    className="w-4 h-4 text-blue-600 border-gray-300 rounded"
                    disabled={isSubmitting}
                  />
                  <label className="text-xs text-gray-500">
                    Auto-generate slug from page name
                  </label>
                </div>
                <p className="text-xs text-gray-400 mt-1">
                  URL-friendly identifier. Use lowercase letters, numbers, and hyphens.
                </p>
              </div>

              {/* Title */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Page Title <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="title"
                  value={formData.title}
                  onChange={handleChange}
                  className={`w-full px-4 py-2.5 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 ${formErrors.title ? 'border-red-500' : 'border-gray-300'
                    }`}
                  placeholder="e.g., About Us - DUS"
                  disabled={isSubmitting}
                />
                {formErrors.title && (
                  <p className="text-red-500 text-xs mt-1">{formErrors.title}</p>
                )}
              </div>

              {/* Description */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description
                </label>
                <textarea
                  name="description"
                  value={formData.description}
                  onChange={handleChange}
                  rows="4"
                  className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 resize-none"
                  placeholder="A brief description of the page for SEO purposes"
                  disabled={isSubmitting}
                />
                <p className="text-xs text-gray-400 mt-1">
                  Optional. Used for SEO and meta description.
                </p>
              </div>

              {/* Status Toggle */}
              <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                <div className="flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${formData.is_active ? 'bg-green-100' : 'bg-gray-200'
                    }`}>
                    {formData.is_active ? (
                      <FaFileAlt className="text-green-600" size={14} />
                    ) : (
                      <FaTimes className="text-gray-500" size={14} />
                    )}
                  </div>
                  <div>
                    <span className="text-sm font-medium text-gray-900">Active</span>
                    <p className="text-xs text-gray-500">
                      Inactive pages won't be accessible on the frontend
                    </p>
                  </div>
                </div>
                <input
                  type="checkbox"
                  name="is_active"
                  checked={formData.is_active}
                  onChange={handleChange}
                  className="w-5 h-5 text-blue-600 focus:ring-blue-500 border-gray-300 rounded transition-all duration-200"
                  disabled={isSubmitting}
                />
              </div>

              {/* Form Actions */}
              <div className="flex justify-end gap-3 pt-6 border-t border-gray-200">
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="px-6 py-2.5 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-all duration-200 font-medium"
                  disabled={isSubmitting}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-6 py-2.5 bg-linear-to-r from-blue-600 to-blue-700 text-white rounded-lg hover:from-blue-700 hover:to-blue-800 transition-all duration-200 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 flex items-center gap-2 font-medium shadow-md"
                >
                  {isSubmitting && <FaSpinner className="animate-spin" size={16} />}
                  <FaSave size={16} />
                  {editingPage ? (isSubmitting ? 'Updating...' : 'Update Page') : (isSubmitting ? 'Creating...' : 'Create Page')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Styles */}
      <style>{`
        @keyframes fade-in {
          from { opacity: 0; transform: scale(0.95); }
          to { opacity: 1; transform: scale(1); }
        }
        .animate-fade-in {
          animation: fade-in 0.2s ease-out;
        }
      `}</style>
    </AuthenticatedLayout>
  );
}